{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "19c0e420_cea42060",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1009116
      },
      "writtenOn": "2022-04-06T17:22:37Z",
      "side": 1,
      "message": "looks correct to me, adding Ade just in case",
      "revId": "01235c1aed5dbc6b29be9b9d40799a9ff688621b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "02997436_07a47e14",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1016110
      },
      "writtenOn": "2022-04-06T19:14:42Z",
      "side": 1,
      "message": "Locally tested and re-run tempest with the option, the ssh-related failures are gone.",
      "revId": "01235c1aed5dbc6b29be9b9d40799a9ff688621b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    }
  ]
}