{
  "comments": [
    {
      "key": {
        "uuid": "db088e8f_3fdc1e5c",
        "filename": "plugins/tripleo-undercloud/restore.yml",
        "patchSetId": 2
      },
      "lineNbr": 130,
      "author": {
        "id": 1001189
      },
      "writtenOn": "2017-11-02T12:08:14Z",
      "side": 1,
      "message": "this is executed on ... hypervisor?\ni guess that\u0027s wrong then,\nshould be run on undercloud, as stack?, and together with sourcing rc file first",
      "revId": "1d1efd953d84eeee9661d518cd509d22a9d073ca",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "075b35a7_5135fca1",
        "filename": "plugins/tripleo-undercloud/restore.yml",
        "patchSetId": 2
      },
      "lineNbr": 134,
      "author": {
        "id": 1001189
      },
      "writtenOn": "2017-11-02T12:08:14Z",
      "side": 1,
      "message": "i believe you do not have ignore_errors/... above so it would fail there anyway - and so no need for explicit fail task?",
      "revId": "1d1efd953d84eeee9661d518cd509d22a9d073ca",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    }
  ]
}