{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "bcedcf4a_34c4378e",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1017703
      },
      "writtenOn": "2022-02-04T19:43:51Z",
      "side": 1,
      "message": "Gates failure appears to be a bug in ansible-lint resulting from a breaking update to rich (rich.console): https://github.com/ansible-community/ansible-lint/issues/1795",
      "revId": "6406d7aa93da3005da6673a767e58e8be13f236b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    }
  ]
}